Rails Projects/photo-app/config/routes.rb
Rails.application.routes.draw do
  resources :images
  devise_for :users, controllers: { registrations: 'users/registrations' }
  root 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

Rails Projects/photo-app/app/models/image.rb
class Image < ApplicationRecord
  validate :picture_size
  belongs_to :user
  mount_uploader :picture, PictureUploader

  private

  def picture_size
    if picture.size > 5.megabytes
      errors.add(:picture, "should be less than 5mb.")
    end
  end
end

Rails Projects/photo-app/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :images
  attr_accessor :stripeToken

  def save_with_subscription
    if valid?
      customer = Stripe::Customer.create(email: email, plan: "PA-0160", source: stripeToken)
      self.stripe_customer_token = customer.id
      save!
    end
  end
end

Rails Projects/photo-app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  # Makes it so you have to log in to use this web app
  before_action :authenticate_user!
  # Configuring parameters for the sign up page.
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  # Long way to sanitize sign_up action
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :password, :password_confirmation, :stripeToken])
  end
end

Rails Projects/photo-app/app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :set_image, only: [:show, :edit, :update, :destroy]

  # GET /images
  # GET /images.json
  def index
    @images = Image.all
  end

  # GET /images/1
  # GET /images/1.json
  def show
  end

  # GET /images/new
  def new
    @image = Image.new
  end

  # GET /images/1/edit
  def edit
  end

  # POST /images
  # POST /images.json
  def create
    @image = Image.new(image_params)
    @image.user = current_user

    respond_to do |format|
      if @image.save
        format.html { redirect_to @image, notice: 'Image was successfully created.' }
        format.json { render :show, status: :created, location: @image }
      else
        format.html { render :new }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /images/1
  # PATCH/PUT /images/1.json
  def update
    respond_to do |format|
      if @image.update(image_params)
        format.html { redirect_to @image, notice: 'Image was successfully updated.' }
        format.json { render :show, status: :ok, location: @image }
      else
        format.html { render :edit }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /images/1
  # DELETE /images/1.json
  def destroy
    @image.destroy
    respond_to do |format|
      format.html { redirect_to images_url, notice: 'Image was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_image
      @image = Image.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def image_params
      params.require(:image).permit(:name, :picture, :user_id)
    end
end

Rails Projects/photo-app/app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  def create
    super do |resource|
      resource.save_with_subscription
    end
  end

  protected
  # Set path after sign up to index.
  def after_sign_up_path_for(resource)
    render 'welcome#index'
  end
end

Rails Projects/photo-app/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index]
  def index
  end
end

Rails Projects/photo-app/app/helpers/images_helper.rb
module ImagesHelper
end

Rails Projects/photo-app/app/helpers/welcome_helper.rb
module WelcomeHelper
end

Rails Projects/photo-app/app/views/images/_form.html.erb
<%= form_for(image, html: { multipart: true }) do |f| %>
  <% if image.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(image.errors.count, "error") %> prohibited this image from being saved:</h2>

      <ul>
      <% image.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :picture %>
    <%= f.file_field :picture, accept: 'image/jpeg, image/gif, image/png', class: "form-control" %>
  </div>

  <div class="actions text-center">
    <%= f.submit "Submit", class: "btn btn-primary btn-lg" %>
  </div>
<% end %>
<script type="text/javascript">
  $("#image_picture").bind("change", function(){
    var size_mb = this.files[0].size/1024/2024;
    if (size_mb > 5) {
      $("#js-alerts").addClass("alert alert-warning text-center").html("The maximum file size is 5MB.");
    }
  });
</script>

Rails Projects/photo-app/app/views/images/edit.html.erb
<div class="col-xl-6 offset-xl-3 pt-5">
  <h1 class="text-center">Editing Image</h1>
  <%= render 'form', image: @image %>
  <div class="text-center">
    <%= link_to 'Show', @image %> |
    <%= link_to 'Back', images_path %>
  </div>
</div>

Rails Projects/photo-app/app/views/images/index.html.erb
<h3 class="display-4 text-center py-5">All Images</h3>
<% @images.each do |image| %>
  <!-- Create grid of uploaded images -->
  <%= link_to image_path(image) do %>
    <%= image_tag image.picture.url, class: "img-thumbnail index-grid" %>
  <% end %>
<% end %>

Rails Projects/photo-app/app/views/images/new.html.erb
<div class="col-xl-6 offset-xl-3 pt-5">
  <h1 class="text-center">New Image</h1>
  <%= render 'form', image: @image %>
  <div class="text-center">
    <%= link_to 'Show', @image %> |
    <%= link_to 'Back', images_path %>
  </div>
</div>

Rails Projects/photo-app/app/views/images/show.html.erb
<div class="my-5 pt-5 pb-0">
  <h3 class="text-center display-4">
    <%= @image.name if @image.name? %>
  </h3>
</div>
<div class="text-center">
  <%= image_tag(@image.picture.url, class: "img-fluid mx-auto") if @image.picture? %>
  <br><br>
  <p class="text-right">
    by <%= @image.user.email %>
  </p>
  <% if @image.user.id == current_user.id %>
    <%= link_to 'Delete', image_path(@image), method: :delete %> |
    <%= link_to 'Edit', edit_image_path(@image) %> |
  <% end %>
  <%= link_to 'Back', images_path %>
</div>

Rails Projects/photo-app/app/views/welcome/index.html.erb
<div class="row">
  <div class="col-xl-12 mx-0 px-0">
    <div class="callToAction img-fluid sticky-top" id="callToAction">
      <div class="col-xl-6 offset-xl-3">
        <h1 class="text-center callToActionText">SHARE YOUR ADVENTURE</h1>
      </div>
    </div>
  </div>
</div>
<div class="row my-5">
  <div class="col-xl-8 offset-xl-2">
    <div class="jumbotron quote-package">
      <h3 class="text-center">
        A picture is worth a thousand words.
        <footer class="blockquote-footer">
          Tony Stark, Parks and Recreations (2019)
        </footer>
      </h3>
    </div>
    <hr class="mt-5">
  </div>
</div>
<div class="row">
  <div class="col-xl-4 offset-xl-4">
    <h3 class="display-3 text-center mb-5">OUR PLANS</h3>
  </div>
  <div class="col-xl-4 offset-xl-2">
    <div class="jumbotron silver-package">
      <h4 class=" display-4 text-center">Professional</h3>
      <h4 class="text-center">$10</h4>
      <p class="text-left my-4 packages ml-3">
        <div class="list-group">
          <div class="list-group-item">
            <%= fa_icon "picture-o", text: "Unlimited Uploads", class: "fa-lg m-2" %><br>
          </div>
          <div class="list-group-item">
            <%= fa_icon "envelope-open", text: "Exclusive Forum Access", class: "fa-lg m-2" %><br>
          </div>
          <div class="list-group-item">
            <%= fa_icon "calendar-check-o", text: "Calendar Access", class: "fa-lg m-2" %><br>
          </div>
          <div class="list-group-item">
            <%= fa_icon "copyright", text: "Copyright Advice", class: "fa-lg m-2" %><br>
          </div>
          <div class="list-group-item">
            <%= fa_icon "podcast", text: "Podcast Access", class: "fa-lg m-2" %><br>
          </div>
          <div class="list-group-item spacer">
          </div>
          <div class="list-group-item spacer">
          </div>
          <div class="list-group-item spacer">
          </div>
        </div>
      </p>
        <%= link_to "Pick Pro", "#", class: "btn btn-outline-primary btn-lg btn-block" %>
    </div>
  </div>
  <div class="col-xl-4">
    <div class="jumbotron gold-package">
      <h4 class=" display-4 text-center">Studio</h3>
      <h4 class="text-center">$20</h4>
      <p class="text-left my-4 packages ml-3">
        <div class="list-group">
          <div class="list-group-item">
            <%= fa_icon "picture-o", text: "Unlimited Uploads", class: "fa-lg m-2" %><br>
          </div>
          <div class="list-group-item">
            <%= fa_icon "envelope-open", text: "Exclusive Forum Access", class: "fa-lg m-2" %><br>
          </div>
          <div class="list-group-item">
            <%= fa_icon "calendar-check-o", text: "Calendar Access", class: "fa-lg m-2" %><br>
          </div>
          <div class="list-group-item">
            <%= fa_icon "copyright", text: "Copyright Advice", class: "fa-lg m-2" %><br>
          </div>
          <div class="list-group-item">
            <%= fa_icon "podcast", text: "Podcast Access", class: "fa-lg m-2" %><br>
          </div>
          <div class="list-group-item">
            <%= fa_icon "area-chart", text: "Analytics", class: "fa-lg m-2" %><br>
          </div>
          <div class="list-group-item">
            <%= fa_icon "lock", text: "Private Albums", class: "fa-lg m-2" %><br>
          </div>
          <div class="list-group-item">
            <%= fa_icon "trophy", text: "Studio Contests", class: "fa-lg m-2" %><br>
          </div>
        </div>
      </p>
      <%= link_to "Pick Studio", "#", class: "btn btn-outline-success btn-lg btn-block" %>
    </div>
  </div>
</div>