Rails Projects/stock-tracker/config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { :registrations => "user/registrations" }
  resources :user_stocks, except: [:show, :edit, :update]
  resources :users, only: [:show]
  resources :friendships
  root 'pages#index'
  get 'my_portfolio', to: 'users#my_portfolio'
  get 'search_stocks', to: 'stocks#search'
  get 'my_friends', to: 'users#my_friends'
  get 'search_friends', to: 'users#search'
  post 'add_friend', to: 'users#add_friend'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

Rails Projects/stock-tracker/app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user
  belongs_to :friend, class_name: 'User'
end

Rails Projects/stock-tracker/app/models/stock.rb
class Stock < ApplicationRecord
  has_many :user_stocks
  has_many :users, through: :user_stocks

  def self.find_by_ticker(ticker_symbol)
    where(ticker: ticker_symbol).first
  end

  def self.new_from_lookup(ticker_symbol)
    looked_up_stock = StockQuote::Stock.quote(ticker_symbol)
    return nil unless looked_up_stock.name

    new_stock = new(ticker: looked_up_stock.symbol, name: looked_up_stock.name)
    new_stock.last_price = new_stock.price
    new_stock
  end

  def price
    closing_price = StockQuote::Stock.quote(ticker).close
    return "#{closing_price} (Closing)" if closing_price

    opening_price = StockQuote::Stock.quote(ticker).open
    return "#{opening_price} (Opening)" if opening_price
    "Unavailable"
  end
end

Rails Projects/stock-tracker/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :user_stocks
  has_many :stocks, through: :user_stocks
  has_many :friendships
  has_many :friends, through: :friendships

  def can_add_stock?(ticker_symbol)
    under_stock_limit? && !stock_already_added?(ticker_symbol)
  end

  def under_stock_limit?
    (user_stocks.count < 10)
  end

  def stock_already_added?(ticker_symbol)
    stock = Stock.find_by_ticker(ticker_symbol)
    return false unless stock
    user_stocks.where(stock_id: stock.id).exists?
  end

  def full_name
    return "#{first_name} #{last_name}".strip if (first_name || last_name)
    "Anonymous"
  end

  def not_friends_with?(friend_id)
    friendships.where(friend_id: friend_id).count < 1
  end

  def except_current_user(users)
    users.reject { |user| user.id == self.id }
  end

  def self.search(param)
    return User.none if param.blank?
    param.strip!
    param.downcase!
    (first_name_matches(param) + last_name_matches(param) + email_matches(param)).uniq
  end

  def self.first_name_matches(param)
    matches('first_name', param)
  end

  def self.last_name_matches(param)
    matches('last_name', param)
  end

  def self.email_matches(param)
    matches('email', param)
  end

  def self.matches(field_name, param)
    where("lower(#{field_name}) LIKE ?", "%#{param}%")
  end
end

Rails Projects/stock-tracker/app/models/user_stock.rb
class UserStock < ApplicationRecord
  belongs_to :user
  belongs_to :stock
end

Rails Projects/stock-tracker/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

Rails Projects/stock-tracker/app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  def destroy
    @friendship = current_user.friendships.where(friend_id: params[:id]).first
    @friendship.destroy
    respond_to do |f|
      f.html { redirect_to my_friends_path }
      notice[:success] = "Friend was successfully removed."
    end
  end
end

Rails Projects/stock-tracker/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index

  end
end

Rails Projects/stock-tracker/app/controllers/stocks_controller.rb
class StocksController < ApplicationController

  def search
    if params[:stock]
      @stock = Stock.find_by_ticker(params[:stock])
      @stock ||= Stock.new_from_lookup(params[:stock])
    end

    if @stock
      # render json: @stock
      render partial: 'lookup'
    else
      render status: :not_found, nothing: true
    end
  end

  def index

  end
end

Rails Projects/stock-tracker/app/controllers/user/registrations_controller.rb
class User::RegistrationsController < Devise::RegistrationsController
  before_filter :configure_permitted_parameters

  protected
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
      devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
    end
end

Rails Projects/stock-tracker/app/controllers/user_stocks_controller.rb
class UserStocksController < ApplicationController
  before_action :set_user_stock, only: [:show, :edit, :update, :destroy]

  # GET /user_stocks
  # GET /user_stocks.json
  def index
    @user_stocks = UserStock.all
  end

  # GET /user_stocks/1
  # GET /user_stocks/1.json
  def show
  end

  # GET /user_stocks/new
  def new
    @user_stock = UserStock.new
  end

  # GET /user_stocks/1/edit
  def edit
  end

  # POST /user_stocks
  # POST /user_stocks.json
  def create
    if params[:stock_id].present?
      @user_stock = UserStock.new(stock_id: params[:stock_id], user: current_user)
    else
      stock = Stock.find_by_ticker(params[:stock_ticker])
      if stock
        @user_stock = UserStock.new(user: current_user, stock: stock)
      else
        stock = Stock.new_from_lookup(params[:stock_ticker])
        if stock.save
          @user_stock = UserStock.new(user: current_user, stock: stock)
        else
          @user_stock = nil
          flash[:danger] = "Stock is not available."
        end
      end
    end

    respond_to do |format|
      if @user_stock.save
        format.html { redirect_to my_portfolio_path }
        format.json { render :show, status: :created, location: @user_stock }
        flash[:success] = "Stock #{@user_stock.stock.ticker} was successfully saved."
      else
        format.html { render :new }
        format.json { render json: @user_stock.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_stocks/1
  # PATCH/PUT /user_stocks/1.json
  def update
    respond_to do |format|
      if @user_stock.update(user_stock_params)
        format.html { redirect_to @user_stock }
        format.json { render :show, status: :ok, location: @user_stock }
        flash[:success] = "Stock #{@user_stock.stock.ticker} was successfully updated."
      else
        format.html { render :edit }
        format.json { render json: @user_stock.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_stocks/1
  # DELETE /user_stocks/1.json
  def destroy
    @user_stock.destroy
    respond_to do |format|
      format.html { redirect_to my_portfolio_path }
      format.json { head :no_content }
      flash[:success] = "Stock #{@user_stock.stock.ticker} was successfully deleted."
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_stock
      @user_stock = UserStock.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_stock_params
      params.require(:user_stock).permit(:user_id, :stock_id)
    end
end

Rails Projects/stock-tracker/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def my_portfolio
    @user_stocks = current_user.stocks
    @user = current_user
  end

  def my_friends
    @friendships = current_user.friends
  end

  def search
    @users = User.search(params[:search_param])

    if @users
      @users = current_user.except_current_user(@users)
      render partial: 'friends/lookup'
    else
      render status: :not_found, nothing: true
    end
  end

  def add_friend
    @friend = User.find(params[:friend])
    current_user.friendships.build(friend_id: @friend.id)

    if current_user.save
      redirect_to my_friends_path
      flash[:success] = "Friend was successfully added."
    else
      redirect_to my_friends_path
      flash[:danger] = "There was an error with adding user as friend."
    end
  end

  def show
    @user = User.find(params[:id])
    @user_stocks = @user.stocks
  end
end

Rails Projects/stock-tracker/app/helpers/user_stocks_helper.rb
module UserStocksHelper
end

Rails Projects/stock-tracker/app/views/common/_alerts.html.erb
<% flash.each do |name, msg| %>
  <%= content_tag :div, class: "alert alert-#{name}" do %>
    <%= msg %>
  <% end %>
<% end %>

Rails Projects/stock-tracker/app/views/common/_spinner.html.erb
<div id="spinner" class="row col-md-12 text-center spinner">
  <h4 class="text-center">Processing...</h4>
</div>

Rails Projects/stock-tracker/app/views/friends/_lookup.html.erb
<div id="friend-lookup" class="my-2">
  <h3 class="text-center my-5">Find Users</h3>
  <%= form_tag search_friends_path, remote: true, id: 'friend-lookup-form',
        class: 'form-group form-inline my-auto', method: :get do %>
    <%= text_field_tag :search_param, params[:search_param], placeholder: "Name or Email", autofocus: true,
        class: "form-control mr-2 col-md-8" %>
    <%= button_to "Find Users", {}, class: "btn btn-outline-success" %>
  <% end %>
  <%= render 'common/spinner' %>
  <% if @users %>
    <% if @users.size > 0 %>
    <div id="friend-lookup-results" class="my-2">
      <table class="table table-striped">
        <thead>
          <tr>
            <th>Name</th>
            <th>Email</th>
            <th colspan="2">Actions</th>
        <tbody>
          <% @users.each do |user| %>
          <tr>
            <td><%= user.full_name %></td>
            <td><%= user.email %></td>
            <td class="text-center">
              <%= link_to "Portfolio", user_path(user), class: 'btn btn-primary btn-sm' %>
              <% if current_user.not_friends_with?(user.id) %>
                <%= link_to "Add Friend", add_friend_path(user: current_user, friend: user), class: 'btn btn-primary btn-sm', method: :post %>
              <% else %>
                <span class="btn btn-outline-success">Friend</span>
              <% end %>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
    <% else %>
      <h3 class="text-center">No people match this search.</h3>
    <% end %>
    </div>
  <% end %>
  <div id="friend-lookup-error">
  </div>
</div> <!-- friend-lookup my-2 -->

Rails Projects/stock-tracker/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Stock Tracker</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-toggleable-md navbar-light bg-faded">
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <%= link_to "Finance Tracker", root_path, class: "navbar-brand" %>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <div class="navbar-nav mr-auto">
          <div class="nav-item active">
            <%= link_to "Stocks", "#", class: "nav-link" %>
          </div>
          <div class="nav-item">
            <%= link_to "Users", "#", class: "nav-link" %>
          </div>
        </div>
        <% if user_signed_in? %>
          <div class="dropdown form-inline">
            <!-- Classes for this link are in SCSS via @extend -->
            <%= link_to("Account", "#", { id: "navbarAccountDropdown", 'data-toggle' => "dropdown" }) %>
            <div class="dropdown-menu">
              <%= link_to "My Friends", my_friends_path, class: "dropdown-item" %>
              <%= link_to "Edit Account", edit_user_registration_path, class: "dropdown-item" %>
              <%= link_to "View Profile", my_portfolio_path, class: "dropdown-item" %>
            </div>
          </div> <!-- nav-item dropdown -->
          <!-- Classes for this link are in SCSS via @extend -->
          <%= link_to "Logout", destroy_user_session_path, id: "btnLogout", method: :delete %>
        <% else %>
          <%= content_tag :div, class: "btn-group ml-2" do %>
            <%= link_to "Log In", new_user_session_path, class: "btn btn-outline-success my-2 my-sm-0" %>
            <%= link_to "Sign Up", new_user_registration_path, class: "btn btn-outline-success my-2 my-sm-0" %>
          <% end %>
        <% end %>
      </div>
    </nav>
    <div class="col-md-4 offset-md-4 my-2" id="alerts">
      <%= render 'common/alerts' %>
    </div>
    <%= yield %>
  </body>
</html>

Rails Projects/stock-tracker/app/views/pages/index.html.erb
PAGES INDEX VIEW

<%= link_to "logout", destroy_user_session_path, method: :delete %>

Rails Projects/stock-tracker/app/views/stocks/_list.html.erb
<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Symbol</th>
      <th>Current Price</th>
      <% if @user.id == current_user.id %>
        <th>Actions</th>
      <% end %>
    </tr>
  </thead>
  <tbody>
    <% @user_stocks.each do |user_stock| %>
      <tr>
        <td><%= user_stock.name %></td>
        <td><%= user_stock.ticker %></td>
        <td><%= user_stock.price %></td>
        <td>
          <% if @user.id == current_user.id %>
            <%= link_to 'Delete', user_stock_path(user_stock), method: :delete, class: "btn btn-danger btn-sm" %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

Rails Projects/stock-tracker/app/views/stocks/_lookup.html.erb
<div id="stock-lookup" class="my-2">
  <h3 class="text-center my-5">Find Stock</h3>
  <%= form_tag search_stocks_path(params[:stock]), remote: true, id: 'stock-lookup-form',
        class: 'form-group form-inline my-auto', method: :get do %>
    <%= text_field_tag :stock, params[:stock], placeholder: "Stock Ticker Symbol", autofocus: true,
        class: "form-control mr-2 col-md-8" %>
    <%= button_to "Find Stock", {}, class: "btn btn-outline-success" %>
  <% end %>
  <%= render 'common/spinner' %>
  <% if @stock %>
    <div id="stock-lookup-results" class="jumbotron my-2">
      <h3><strong>Symbol:</strong> <%= @stock.ticker %></h3>
      <p><strong>Name:</strong> <%= @stock.name %></p>
      <p><strong>Price:</strong> <%= @stock.price %></p>
      <% if current_user.can_add_stock?(@stock.ticker) %>
        <p class="text-center">
          <%= link_to "Add To Portfolio", user_stocks_path(user: current_user, stock_ticker: @stock.ticker, stock_id: @stock.id ? @stock.id : ''), class: 'btn btn-outline-success', method: :post %>
        </p>
      <% else %>
        <span class="label label-default">
          Stock cannot be added because you have already added
          <% if !current_user.under_stock_limit? %>
          10 stocks
          <% end %>
          <% if current_user.stock_already_added?(@stock.ticker) %>
          this stock.
          <% end %>
        </span>
      <% end %>
    </div>
  <% end %>
  <div id="stock-lookup-error">
  </div>
</div> <!-- stock-lookup my-2 -->