Rails Projects/alpha-blog/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'pages#home'
  get 'about', to: 'pages#about'
  resources :users, except: [:new]
  get 'signup', to: 'users#new'
  post 'admin/:id' => 'users#make_admin', as: "make_admin"
  # START sessions
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  # END sessions
  resources :articles
  resources :categories, except: [:destroy]
end

Rails Projects/alpha-blog/app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :user
  has_many :article_categories
  has_many :categories, through: :article_categories
  validates :title, presence: true, length: { minimum: 3, maximum: 50 }
  validates :description, presence: true, length: { minimum: 10 }
  validates :body, presence: true, length: { minimum: 10, maximum: 1000 }
  validates :user_id, presence: true
end

Rails Projects/alpha-blog/app/models/article_category.rb
class ArticleCategory < ActiveRecord::Base
  belongs_to :article
  belongs_to :category
end

Rails Projects/alpha-blog/app/models/category.rb
class Category < ActiveRecord::Base
  has_many :article_categories
  has_many :articles, through: :article_categories
  validates :name, presence: true, length: { minimum: 3, maximum: 25 }
  validates_uniqueness_of :name
end

Rails Projects/alpha-blog/app/models/user.rb
class User < ActiveRecord::Base
  has_many :articles, dependent: :destroy
  before_save { self.email = email.downcase }
  validates :username,
            presence: true,
            uniqueness: { case_sensitive: false },
            length: { minimum: 3, maximum: 10 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email,
            presence: true, uniqueness: { case_sensitive: false },
            length: { maximum: 100 },
            format: { with: VALID_EMAIL_REGEX }
  has_secure_password
end

Rails Projects/alpha-blog/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user, :logged_in?, :toggle_admin

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:warning] = "You must be logged in to access this page."
      redirect_to root_path
    end
  end

  def toggle_admin
    if logged_in?
      user.toggle!(:admin)
    end
  end
end

Rails Projects/alpha-blog/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:edit, :update, :show, :destroy]
  before_action :require_user, except: [:index, :show]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  def index
    @articles = Article.order("id DESC").page(params[:page])
    respond_to do |f|
      f.html { render 'index' }
      f.js { render layout: false }
    end
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    @article.user = current_user
    if @article.save
      flash[:success] = "Article was successfully created."
      redirect_to article_path(@article)
    else
      flash[:danger] = "The article could not be saved."
      render :new
    end
  end

  def edit

  end

  def update
    if @article.update(article_params)
      flash[:success] = "The article was successfully updated."
      redirect_to article_path(@article)
    else
      render :edit
    end
  end

  def show

  end

  def destroy
    @article.destroy
    flash[:success] = "Article was successfully deleted."
    redirect_to articles_path
  end

  private
    def article_params
      params.require(:article).permit(:title, :description, :body, :user_id, category_ids: [])
    end

    def set_article
      @article = Article.find(params[:id])
    end

    def require_same_user
      if current_user != @article.user and !current_user.admin?
        flash[:warning] = "You can only edit or delete your own articles."
        redirect_to root_path
      end
    end
end

Rails Projects/alpha-blog/app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :require_admin, except: [:index, :show]

  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:success] = "Category created!"
      redirect_to categories_path
    else
      @category.errors.full_messages.each do |msg|
        flash[:danger] = msg
      end
      render 'new'
    end
  end

  def show
    @category = Category.find(params[:id])
    @category_articles = @category.articles.order("id DESC").page(params[:page])
    respond_to do |f|
      f.html
      f.js { render layout: false }
    end
  end

  private
    def category_params
      params.require(:category).permit(:name)
    end

    def require_admin
      if !logged_in? || (logged_in? && !current_user.admin?)
        flash[:warning] = "Only administrators can perform that action."
        redirect_to categories_path
      end
    end

end

Rails Projects/alpha-blog/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    redirect_to articles_path if logged_in?
  end

  def about

  end
end

Rails Projects/alpha-blog/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new

  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:success] = "Successfully logged in!"
      redirect_to user_path(user)
    else
      flash.now[:warning] = "There was something wrong with your login information."
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = "You have logged out."
    redirect_to root_path
  end
end

Rails Projects/alpha-blog/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:edit, :update, :show, :make_admin]
  before_action :require_same_user, only: [:edit, :update, :destroy]
  before_action :require_admin, only: [:destroy]

  def index
    @users = User.page(params[:page])
    respond_to do |f|
      f.html
      f.js { render layout: false }
    end
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:success] = "Welcome to Alpha Blog, #{@user.username}!"
      redirect_to user_path(@user)
    else
      @user.errors.full_messages.each do |msg|
        flash[:danger] = msg
      end
      render 'new'
    end
  end

  def edit

  end

  def make_admin
    @user.toggle!(:admin)
    redirect_to users_path
  end

  def update
    if @user.update(user_params)
      flash[:success] = "Your account was updated successfully!"
      redirect_to articles_path
    else
      render 'edit'
    end
  end

  def show
    @user_articles = @user.articles.order("id DESC").page(params[:page])
    respond_to do |f|
      f.html
      f.js { render format: false }
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    flash[:danger] = "User and all articles have been deleted."
    redirect_to users_path
  end

  private
    def user_params
      params.require(:user).permit(:username, :email, :password)
    end

    def set_user
      @user = User.find(params[:id])
    end

    def require_same_user
      if current_user.id != @user.id && !current_user.admin?
        flash[:warning] = "You can only edit your own profile."
        redirect_to root_path
      end
    end

    def require_admin
      if logged_in && !current_user.admin?
        flash[:warning] = "Only admin users can perform that action."
        redirect_to root_path
      end
    end
end

Rails Projects/alpha-blog/app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.username, class: "img-thumbnail")
  end
end

Rails Projects/alpha-blog/app/views/articles/_form.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-4 offset-md-4">
      <%= form_for @article, html: { id: "articleForm" } do |f| %>
        <div class="form-group">
          <div class="form-group" id="formGroupTitle">
            <%= f.label :title, class: "form-control-label", for: "title" %>
            <%= f.text_field :title, class: "form-control form-control-warning", id: "title", maxlength: 50 %>
          </div>
          <div class="form-group" id="formGroupDesc">
            <%= f.label :description, class: "form-control-label", for: "description" %>
            <%= f.text_area :description, class: "form-control form-control-warning article-description",
                id: "description", maxlength: 140 %>
          </div>
          <div class="form-group" id="formGroupBody">
            <%= f.label :body, class: "form-control-label", for: "body" %>
            <%= f.text_area :body, class: "form-control form-control-warning article-body",
                id: "description", maxlength: 1000 %>
          </div>
          <div class="form-group" id="formGroupCategories">
            <h4 class="text-center mb-3">Categories</h4>
            <%= f.collection_select(:category_ids, Category.all, :id, :name, {}, { class: "categorySelect form-control", id: "categorySelect", multiple: true } ) %>
          </div>
          <%= f.submit "Submit", class: "btn btn-primary btn-lg btn-block", id: "btnSubmitArticle" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

Rails Projects/alpha-blog/app/views/articles/_show-articles.html.erb
<% obj.each do |article| %>
  <div class="jumbotron p-4">
    <div class="container">
      <h3><%= link_to article.title, article_path(article.id) %></h3>
        <% if article.user %>
         <em>
           by <%= link_to article.user.username, user_path(article.user) %>
        </em>
        <% end %>
      <hr>
      <%= article.description %><br>
      <% if article.categories.any? %>
        <%= render article.categories %>
      <% end %>
      <p class="text-right">
        <% if  logged_in? && (current_user == article.user || current_user.admin?) %>
          <%= link_to "Edit", edit_article_path(article.id), class: "btn btn-secondary btn-sm" %>
          <%= link_to "View", article_path(article.id), class: "btn btn-secondary btn-sm" %>
          <%= link_to "Delete", article_path(article.id), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger btn-sm" %>
        <% end %>
      </p>
    </div>
  </div>
<% end %>

Rails Projects/alpha-blog/app/views/articles/edit.html.erb
<h1 class='text-center'>Edit Article</h1>
<%= render 'form' %>

Rails Projects/alpha-blog/app/views/articles/index.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-2">
      <!-- Perhaps a sidebar? -->
    </div>
    <div class="col-md-6 offset-md-1">
      <h1 class="text-center">Articles</h1>
      <div class="col-md-4 offset-md-4">
        <% if logged_in? %>
          <%= link_to "New Article", new_article_path, class: "btn btn-primary text-center btn-lg btn-block" %>
        <% end %>
      </div>
      <br>
      <%= paginate @articles %>
      <div class="articlesIndex" id="articlesIndex">
        <%= render 'show-articles', obj: @articles %>
      </div>
      <p class="pagination">
        <%= link_to_next_page(@articles, 'Next Page', remote: true) %>
      </p>
    </div> <!-- col-md-8 -->
  </div> <!-- row -->
</div> <!-- container -->

Rails Projects/alpha-blog/app/views/articles/index.js.erb
// Append new data
$("<%= j render('show-articles', obj: @articles) %>")
  .appendTo($("#articlesIndex"));

// Update pagination link
<% if @articles.last_page? %>
  $('.pagination').html("That's all, folks!");
<% else %>
  $('.pagination')
    .html("<%= j link_to_next_page(@articles, 'Next Page', remote: true) %>");
<% end %>

Rails Projects/alpha-blog/app/views/articles/new.html.erb
<h1 class='text-center'>New Article</h1>
<%= render 'form' %>

Rails Projects/alpha-blog/app/views/articles/show.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-6 offset-md-3">
      <h1 class="text-center">View Article</h1><br>
      <% if @article.user %>
        <h3 class="text-center"><%= link_to @article.user.username, user_path(@article.user) %></h3><br>
        <p class="text-center">
          <%= link_to gravatar_for(@article.user), user_path(@article.user) %>
        </p>
      <% end %>
      <h3 class="text-center"> <%= @article.title %> </h3><br>
      <p> <strong>Description: </strong><%= @article.description %> </p>
      <hr>
      <p> <%= @article.body %> </p>
      <% if @article.categories.any? %>
        <p>
          <%= render @article.categories %>
        </p>
      <% end %>
    </div>
  </div>
</div>

Rails Projects/alpha-blog/app/views/pages/about.html.erb
This is the about page.

Rails Projects/alpha-blog/app/views/pages/home.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-8 offset-md-2">
      <div class="jumbotron call-to-action">
        <h1 class="text-center text-white">Alpha Blog</h1><br>
        <p class="text-left text-white">
          Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
        </p><br><br><br><br>
          <p class="text-center align-bottom">
            <%= link_to "Sign Up", signup_path, class: "btn btn-primary btn-lg" %>
          </p>
        </div>
      </div> <!-- jumbotron -->
    </div> <!-- col-md-8 offset-md-2 -->
  </div> <!-- row -->
</div> <!-- container-fluid -->